

variables:      # pipeline-level
  MY_VAR: 'my value'
  ANOTHER_VAR: 'another value'

stages:
- stage: Build Model
  variables:    # stage-level
    STAGE_VAR: 'that happened'

  jobs:
  - job: Build_and_Publish_Model
    variables:  # job-level
      JOB_VAR: 'a job var'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6

- stage: Deploy Model To ACI
  variables:    # stage-level
    STAGE_VAR: 'that happened'

  jobs:
  - job: Build_and_Publish_Model
    variables:  # job-level
      JOB_VAR: 'a job var'
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'AMLSP'
        scriptLocation: 'inlineScript'
        inlineScript: 'echo "hi"'

